### ISSUE TITLE
Export system failure on hashing token for accounts check

### ISSUE THREAD

**Issue by michaelcerne** [michaelcerne/myrealcontacts#3]
`(node:32063) UnhandledPromiseRejectionWarning: TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:99:16)
    at AccountsServer.Ap._hashLoginToken (packages/accounts-base/accounts_server.js:824:8)
    at WebApp.connectHandlers.use (server/main.js:43:57)
    at /services/web/mrc/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
(node:32063) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:32063) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Stemming from updates done to correct linting on main.js

**Comment by michaelcerne** [comment]
Corrected (https://github.com/michaelcerne/myrealcontacts/commit/dadce60c9ead58d17885dc4b389f5128ecee3dab). System was not correctly checking if a value was undefined, throwing off every following value.
